#!/bin/bash

SCRIPT_DIR="$HOME/.local/share/tmux-scripts"

usage(){
    echo ""
    echo "Usage: $0 [-h] <script-name>"
    echo ""
    echo "Option:"
    echo "  -h          Display the help message."
    echo ""
}

while getopts "h" opt; do
	case "${opt}" in
		h) usage
			exit 0
			;;
        \?) # Invalid option
            echo "Invalid option: -$OPTARG"
            usage
            exit 1
            ;;
	esac
done

if [[ -z "$1" ]]; then
	echo "Error: script name is empty"
	exit 1
fi

: << "COMMENT"
if [[ ! -f "$SCRIPT_DIR/$1" ]]; then
	echo "Error: script '$1' not found"
	exit 1
fi
if [[ ! -x "$SCRIPT_DIR/$1" ]]; then
	echo "Error: script '$1' not executable"
	exit 1
fi
COMMENT
scriptName=$1
shift

echo "Executing tmux script: '$scriptName'"
sh "$SCRIPT_DIR/$scriptName.sh" "$@"
